---
version: '3.9'

services:
  nginx:
    build: ./nginx/
    ports:
      - 443:443
      - 80:80
      - 3000:3000
    volumes:
      - ./nginx/${RTE:-dev}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static/
      - ./pages:/etc/nginx/html
      - ./certs/:/etc/letsencrypt/
